plugins {
	id 'com.android.library'
	id 'maven-publish'
}

android {
	namespace 'com.azoft.carousellayoutmanager'
	compileSdkVersion androidCompileSdkVersion

	defaultConfig {
		minSdkVersion androidMinSdkVersion
		targetSdkVersion androidTargetSdkVersion
	}

	configurations {
		documentation
	}
	publishing {
		singleVariant("release")
	}
}

dependencies {
	implementation "androidx.annotation:annotation:1.9.1"
	implementation "androidx.recyclerview:recyclerview:1.4.0"
	implementation "androidx.appcompat:appcompat:1.7.1"
}

afterEvaluate {
	publishing {
		publications {
			release(MavenPublication) {
				from components["release"]

				groupId = 'com.github.PatrinAV'
				artifactId = 'CarouselLayoutManager'
				version = '1.1.18'

				pom {
					name.set('CarouselLayoutManager')
				}
			}
		}
	}
}
